name: SkyBlock
version: 1.0
author: Cheftoaster
depend: [WorldGuard, WorldEdit]

main: net.MyCliff.SkyBlock.Main

commands:
  insel:
    description: island command
    aliases: [is, island]

  villager:
    description: villager command

  version:
    description: SkyBlock version
    aliases: [sversion, sv, skyblockversion]

  fly:
    description: Fly Command