name: SkyBlock
version: 1.0
authors: [Cheftoaster, Monty]
depend: [WorldGuard, WorldEdit]

main: net.MyCliff.SkyBlock.Main

commands:
  insel:
    description: island command
    aliases: [is, island]